[package]
name = "ocaml-derive"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
proc-macro = true
doctest = false

[dependencies]
syn = { version = "1.0.76", features = ["full"] }
quote = "1.0.9"
proc-macro2 = "1.0.29"
convert_case = "0.5.0"
