[package]
name = "ocaml-gen-derive"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "The inner library of ocaml-gen, for generating OCaml code"
repository = "https://github.com/o1-labs/ocaml-gen"

[lib]
proc-macro = true
doctest = false

[dependencies]
syn = { version = "1.0.76", features = ["full"] }
quote = "1.0.9"
proc-macro2 = "1.0.29"
convert_case = "0.5.0"
