[package]
name = "ocaml-gen"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "A library for generating OCaml code"
repository = "https://github.com/o1-labs/ocaml-gen"

[lib]
doctest = false

[dependencies]
ocaml-gen-derive = { path = "./derive", version = "0.1.0" }
ocaml = { version = "0.22.2" }
const-random = "0.1.13"
paste = "1.0.5"
