[package]
name = "ocaml-gen"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
doctest = false

[dependencies]
ocaml-derive = { path = "./derive" }
ocaml = { version = "0.22.2" }
const-random = "0.1.13"
paste = "1.0.5"
